const Icons = {
	"facebook": "fab fa-facebook-f fa-fw",
	"google": "fab fa-google fa-fw",
	"iconBrand": "fas fa-laugh-wink",
	"notification": "fas fa-bell fa-fw",
	'signout': "fas fa-sign-out-alt",
	"document": "fas fa-file-alt",
	"dashboard": "fas fa-fw fa-tachometer-alt",
	"emptyset": "fas fa-empty-set",
	"folder": "fas fa-fw fa-folder",
	"toparrow": "fas fa-angle-up",
	"users": "fas fa-users",
	"home": "fas fa-home",
	"user": "fas fa-user",
	"view": "fas fa-eye",
	"edit": "fas fa-edit",
	"delete": "fas fa-trash-alt",
	"plus": "fas fa-plus-square",
	"print": "fas fa-print",
	"table": "fas fa-table",
	"save": "fas fa-save",
	"cancel": "fas fa-window-close",
	"fatura": "fas fa-money-check-alt",
	"report": "fas fa-bug",
	"password": "fas fa-key",
};

export default Icons;